feat(social): create social features
PeruibeTEC/Server pull request #28
Opened 2021-04-18 14:55 UTC by hmartiins

### **Proposed changes**

create social features

<br>

### **Additional Information**

2021-04-19 22:13 UTC, devLeSilverio requested changes
Everything seems to make a lot of sense, I just found syntax errors, other than that LGTM!

2021-04-19 22:13 UTC, devLeSilverio commented on src/modules/social/services/photoPost/DeletePhotoPostService.ts
> +      throw new AppError('Tourist Spot Photo not found.', 404);
This error message should be:
Post Photo not found.

2021-04-19 22:13 UTC, devLeSilverio commented on src/modules/social/services/photoPost/DeletePhotoPostService.ts
> +    deleteImage('tourist-spot-images', photoPost.url);
This should be called:
'post-images'

2021-04-19 22:13 UTC, devLeSilverio commented on src/modules/social/services/photoPost/ShowPhotoPostService.ts
> +export default class DeletePhotoPostService {
This should be called:
ShowPhotoPostService

2021-04-19 22:13 UTC, devLeSilverio commented on src/modules/social/services/post/UpdatePostService.ts
> +export default class UpdateInterestPointService {
This should be called:
UpdatePostService

2021-04-20 00:12 UTC, hmartiins commented
@devLeSilverio I just corrected what you asked for, I don't even know how I missed it lol

2021-04-20 01:44 UTC, devLeSilverio commented
Normal, LGTML!!

2021-04-20 01:44 UTC, merged