Create event user features
PeruibeTEC/Server pull request #30
Opened 2021-04-21 22:43 UTC by joaovds

### **Proposed changes**

**Creates as functions and handling of Event-User and Event-Type-User**

<br>

### **Additional Information**

2021-04-22 11:31 UTC, hmartiins requested changes

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/services/eventUser/UpdateEventUserService.ts
> +      throw new AppError('This event does not belong to this user.', 404);
http code 409 is a correct http code

```ts
 throw new AppError('This event does not belong to this user.', 409);
 ```

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/services/eventUser/UpdateEventUserService.ts
> +      throw new AppError('The date provided is not valid', 400);
http code 412 is a correct http code

```ts
 throw new AppError('This event does not belong to this user.', 412);
```

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/infra/typeorm/repositories/EventUserRepository.ts
> +  public async findAllEventUser(user_id?: string): Promise<EventUser[]> {
the ideal would be to separate this function in two, one responsible only for the Index and the other for showing the user's events. This function currently breaks the Single-responsibility principle.

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/repositories/IEventUserRepository.ts
> +  findAllEventUser(user_id?: string): Promise<EventUser[]>;
same thing as the previous review, separate this function into two

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/services/eventTypeUser/CreateEventTypeUserService.ts
> +    const eventTypeUser = await this.eventTypeUserRepository.create({ name });
check that the same name does not exist in the database before creating

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/services/eventUser/CreateEventUserService.ts
> +    );
```ts
    const thisDateisAfter = await this.dateFnsProvider.thisDateIsAfter(
      String(date)
    );
   ```
   
   do it this way, as there is no need to create a constant in memory just to store stringDate

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/services/eventUser/CreateEventUserService.ts
> +      throw new AppError('The date provided is not valid', 400);
http code 412 is a correct http code
```ts
  throw new AppError('The date provided is not valid', 412);
```

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/services/eventUser/DeleteEventUserService.ts
> +      throw new AppError('This event does not belong to this user.', 404);
http code 409 is a correct http code

```ts
  throw new AppError('This event does not belong to this user.', 409);
```

2021-04-22 11:31 UTC, hmartiins commented on src/modules/event/infra/http/routes/eventUser.routes.ts
> +
when you finish passing ensureAuthenticate on all routes, you can do

```ts
  eventUserRoutes.use(ensureAuthenticate);
```

2021-04-22 12:17 UTC, devLeSilverio requested changes
I found the logic you used to make the business rule very interesting, I just found some mistakes, despite that, LGTM!

2021-04-22 12:17 UTC, devLeSilverio commented on src/modules/event/infra/http/routes/eventTypeUser.routes.ts
> +
Routes are missing authentication
`import ensureAuthenticate from '@shared/infra/http/middlewares/ensureAuthenticate';`
` eventTypeUserRoutes.use(ensureAuthenticate);`

2021-04-22 12:17 UTC, devLeSilverio commented on src/modules/event/infra/http/controllers/EventTypeUserController.ts
> +    const { event_type_id } = request.params;
If you prefer, it would be interesting to keep the code pattern and do the delete function by getting the id by request.body : )

2021-04-26 16:48 UTC, hmartiins approved these changes
lgtm !!

2021-04-27 23:20 UTC, devLeSilverio approved these changes
LGTM !!

2021-04-27 23:21 UTC, merged