refactor(user) create user refactor
PeruibeTEC/Server pull request #32
Opened 2021-05-09 18:45 UTC by devLeSilverio

### **Proposed changes**

       I added the background photo and refactored the index function.

<br>

### **Additional Information**

2021-05-10 11:05 UTC, hmartiins requested changes

2021-05-10 11:05 UTC, hmartiins commented on src/modules/user/services/CreateUserService.ts
> +    if (photo === undefined || background_photo === undefined) {
There is a logical error here.

Let's assume that a user has a profile photo, but does not have a background_photo, if that happens, this code snippet will leave the user with the default profile photo, because when the background_photo is undefined it will enter that if.

2021-05-10 11:05 UTC, hmartiins commented on src/modules/user/services/CreateUserService.ts
> +    background_photo = azureCreate('background-photo', background_photo);
Check if there is something in background_photo, if it exists, then save the photo

```ts
if (background_photo){
  background_photo = azureCreate('background-photo', background_photo);
} else {
  background_photo = false;
}
```

2021-05-10 11:05 UTC, hmartiins commented on src/modules/user/infra/http/controllers/UserController.ts
We have to add a user show, we only have one for the user who is logged in the system, so as not to give the controller a problem, as there are two show methods on the controller, you can create a new controller called ProfileController and put the show current method on it.

2021-05-10 11:50 UTC, devLeSilverio commented on src/modules/user/services/CreateUserService.ts
> +    background_photo = azureCreate('background-photo', background_photo);
I swear I didn't think that lol, I just wanted to enjoy the same "if", I'll fix it!

2021-05-11 00:56 UTC, hmartiins requested changes

2021-05-11 00:56 UTC, hmartiins commented on src/modules/user/infra/http/controllers/ProfileUserController.ts
> +export default class ProjectController {
ProjectController ?
🤔

2021-05-11 00:56 UTC, hmartiins commented on src/modules/user/services/ShowProfileUserService.ts
> +export default class ShowProfileService {
```suggestion
export default class ShowProfileUserService {
```

Thus, the name of the class is semantic with the name of the file

2021-05-11 10:19 UTC, hmartiins approved these changes
lgtm !

2021-05-11 10:20 UTC, merged