feat(business): Create business features
PeruibeTEC/Server pull request #33
Opened 2021-05-10 14:53 UTC by PocketLocked

### **Proposed changes**

Created all business features

<br>

### **Additional Information**

2021-05-11 01:39 UTC, hmartiins requested changes

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/dtos/IBusinessProductDTO.ts
> +  url: string;
change the name of this variable to make it more descriptive
```suggestion
  photo_product_url: string;
```

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessCommentController.ts
> +    const { content, user_id, business_id } = request.body;
it would be interesting if you took the user_id through request.user.id, as it is only possible to create a comment if the user is logged in

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessCommentController.ts
> +  public async showUser(
showUser ? 
🤔

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessCommentController.ts
> +  public async showBusiness(
showBusiness ?
🤔

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessCommentController.ts
> +    await deleteBusinessCommentService.execute({ business_comment_id });
get user.id through request.user.id, and check that this id is the same as the user_id of the comment

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessCommentController.ts
> +    const business = await updateBusinessCommentService.execute({
get user.id through request.user.id, and check that this id is the same as the user_id of the comment

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessContactController.ts
> +    const { business_contact_id } = request.body;
get the contact through business_id and not business_contact_id

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessLocationController.ts
> +  public async show(request: Request, response: Response): Promise<Response> {
get the location through business_id and not business_location_id

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessProductController.ts
> +  public async index(request: Request, response: Response): Promise<Response> {
the interesting thing here would be to make an index based on the business. We pass the business_id and get the products related to it

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessRatingController.ts
> +  public async showUser(
showRatingByUser

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessRatingController.ts
> +  public async showBusiness(
showRatingByBusiness

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessRatingController.ts
> +  public async showAverage(
it is good that you use the showAvarage function within the showBusiness

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessRatingController.ts
> +  public async update(request: Request, response: Response): Promise<Response> {
get the user.id and check that the rating user_id is the same as the id of user.id

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/routes/business.routes.ts
> +businessRouter.delete('/', businessController.delete);
separate delete and put routes in a file only for routes that need authentication

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/routes/businesscomment.routes.ts
> +
insert middleware ensureAuthenticate on that route

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/http/routes/businessrating.routes.ts
> +
insert middleware ensure authenticate on that route

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/infra/typeorm/repositories/BusinessProductRepository.ts
> +
It would be interesting to create one, findAllProductsByBusiness

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/repositories/IBusinessContactRepository.ts
> +  findAllBusinessContact(): Promise<BusinessContact[]>;
It would be interesting to create one, findByBusiness

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/repositories/IBusinessProductRepository.ts
> +  findAllBusinessProduct(): Promise<BusinessProduct[]>;
It would be interesting to create one, findAllProductsByBusiness

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/repositories/IEventBusinessRepository.ts
> +  findAllEventBusiness(): Promise<EventBusiness[]>;
It would be interesting to create one, findEventsByBusiness

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/businessComment/ShowBusinessCommentByBusinessService.ts
> +export default class ShowBusinessCommentService {
The ideal here would be an Index, not a Show if I'm not mistaken

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/businessComment/ShowBusinessCommentByUserService.ts
> +export default class ShowBusinessCommentService {
The ideal here would be an Index, not a Show if I'm not mistaken

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/businessComment/UpdateBusinessCommentService.ts
> +      throw new AppError('Comment  not found.', 404);
```suggestion
      throw new AppError('Comment not found.', 404);
```
there are double spaces here

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/businessLocation/UpdateBusinessLocationService.ts
> +      throw new AppError('Business  not found.', 404);
```suggestion
      throw new AppError('Business not found.', 404);
```
there are double spaces here

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/businessRating/CreateBusinessRatingService.ts
> +
remember to check if the user has not already evaluated this business

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/businessRating/UpdateBusinessRatingService.ts
> +      throw new AppError('Rating  not found.', 404);
```suggestion
      throw new AppError('Rating not found.', 404);
```
there a double space here

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/eventBusiness/DeleteEventBusinessService.ts
> +      throw new AppError('Event Type Business not found.', 404);
```suggestion
      throw new AppError('Event not found.', 404);
```

2021-05-11 01:39 UTC, hmartiins commented on src/modules/business/services/eventBusiness/UpdateEventBusinessService.ts
> +      throw new AppError('Business Type not found.', 404);
```suggestion
      throw new AppError('Business Event not found.', 404);
```

2021-05-11 05:43 UTC, devLeSilverio requested changes
In spite of everything, congratulations for the logic in all the files!!

2021-05-11 05:43 UTC, devLeSilverio commented on src/modules/business/dtos/IBusinessContactDTO.ts
> +  cellphone: string;
Don't forget to leave these attributes null

` cellphone?: string;`
` telephone?: string;`

2021-05-11 05:43 UTC, devLeSilverio commented on src/modules/business/dtos/IBusinessDTO.ts
> +  description: string;
Don't forget to leave these attributes null

`description?: string`
`profile_photo?: string;`
`background_photo?: string;`

2021-05-11 05:43 UTC, devLeSilverio commented on src/modules/business/dtos/IEventBusinessDTO.ts
> +  background_photo: string;
Don't forget to leave these attributes null

`background_photo?: string;`

2021-05-11 05:43 UTC, devLeSilverio commented on src/modules/business/services/business/CreateBusinessService.ts
> +        'https://peruibetec.blob.core.windows.net/business-images/default.jpg';
I think it is better not to put a default image in the background and let it do it in the front end.

2021-05-19 19:59 UTC, hmartiins requested changes

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/services/businessRating/UpdateBusinessRatingService.ts
> +    const checkRatingSize = value;
there is no need to create a checkRatingSize variable, if you just check the value it is understandable that you are checking if it is greater than 5

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/services/businessRating/ShowBusinessRatingByUserService.ts
> +      throw new AppError('User not found.', 404);
just return an empty array, as a user not rating a trade would not be an error

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/services/businessLocation/UpdateBusinessLocationService.ts
> +
remember to approve the verification only if the business_id passed is the same as the business_id of the location

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/services/eventBusiness/DeleteEventBusinessService.ts
> +
just delete if the business_id is the same as the business_id registered at the event

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/services/business/UpdateBusinessService.ts
> +    // todo: put all missing IRequest placeholdes
I think it shouldn't be here lol

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/EventBusinessController.ts
> +      business_id,
get business_id at request.business.id

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/EventBusinessController.ts
> +      business_id,
get business_id at request.business.id

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessRatingController.ts
> +    const { business_id } = request.body;
get business_id at request.business.id

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessLocationController.ts
> +      business_id,
get business_id at request.business.id

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessLocationController.ts
> +    const { business_id } = request.body;
get business_id at request.business.id

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessLocationController.ts
> +      business_id,
get business_id at request.business.id

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessContactController.ts
> +    const { contact_email, cellphone, tellphone, business_id } = request.body;
get business_id at request.business.id

2021-05-19 19:59 UTC, hmartiins commented on src/modules/business/infra/http/controllers/BusinessContactController.ts
> +  public async create(request: Request, response: Response): Promise<Response> {
it is very likely that you have to separate the create, delete and update method in a file of specific routes, as they hold the need for the business to be logged into the application

2021-05-22 21:54 UTC, hmartiins approved these changes
lgtm

2021-05-22 21:58 UTC, devLeSilverio approved these changes
LGTM, congratulations for the effort...

2021-05-23 00:08 UTC, merged